### ISSUE TITLE
Colisão

### ISSUE THREAD

**Issue by ppedra** [ped4735/SA2#1]
as colisoes não estão funcionando direito.
o halt() lá impedia o hero de sair do tile. ele zerava a velocidade sempre, então o hero nunca tinha velocidade para sair do tile.
talvez podemos ter o 'colision enter' só rodando quando ele entra mesmo, não sempre que houver o contato... bom, é uma ideia

**Comment by ped4735** [comment]
Ja funciona assim o collision enter, eu acabei de criar o collisionStay esse sim fica rodando o tempo todo.

**Comment by ppedra** [comment]
joia. tava até na dúvida se vc tinha lido
